### ISSUE TITLE
400 Error

### ISSUE THREAD

**Issue by Besstrashnyy** [barentswatch/barentswatch-api-examples#1]
The link raise an issue 
https://code.barentswatch.net/wiki/display/BWOPEN/API-Documentation

**Comment by bakk** [comment]
The correct link is https://wiki.barentswatch.net/display/BO/Application+registration+and+authentication
I have updated readme.md. Thank you for notifying us!

**Comment by Besstrashnyy** [comment]
Takk, Anders.

PS C:\...\barentswatch-api-examples-master> python authentication.py
Requesting token from https://id.barentswatch.no/connect/token, using
client_id andrei%40ecto.com%3Abarrentswatchapi.
Traceback (most recent call last):
  File "C:\...\barentswatch-api-examples-master\authentication.py", line
28, in <module>
    token = get_token()
  File "C:\...\barentswatch-api-examples-master\authentication.py", line
21, in get_token
    req.raise_for_status()
  File "C:\...\Python\Python39\lib\site-packages\requests\models.py", line
943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url:
https://id.barentswatch.no/connect/token

Jeg får også denne HTTPError når jeg åpne authentication.py.
Jeg sjekket, og client_id og client_secret er riktig, url også, så jeg er
litt usikkert, hva er galt.

пн, 29 мар. 2021 г. в 15:38, Anders Bakkevold ***@***.***>:
